spring:
    cloud:
        gateway:
            routes:
            - id : msvc-products
              uri : lb://msvc-products
              predicates:
              - Path=/api/products**
              filters:
              - StripPrefix=2

            - id : msv-items
              uri : lb://msv-items
              predicates:
              - Path=/api/items**
              filters:
              - StripPrefix=2  